package com.example.product.constants;

public enum PermissionEnum {
    // USER
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,
    GET_USER_BY_ID,
    GET_USERS,

    // CATEGORY
    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,
    GET_CATEGORY_BY_ID,
    GET_CATEGORIES,

    // ACCOUNT_IMAGE
    CREATE_ACCOUNT_IMAGE,
    UPDATE_ACCOUNT_IMAGE,
    DELETE_ACCOUNT_IMAGE,
    GET_ACCOUNT_IMAGE_BY_ID,
    GET_ACCOUNT_IMAGES,

    // ADDRESS
    CREATE_ADDRESS,
    UPDATE_ADDRESS,
    DELETE_ADDRESS,
    GET_ADDRESS_BY_ID,
    GET_ADDRESSES,

    // CUSTOMER
    CREATE_CUSTOMER,
    UPDATE_CUSTOMER,
    DELETE_CUSTOMER,
    GET_CUSTOMER_BY_ID,
    GET_CUSTOMERS,

    // DISCOUNT
    CREATE_DISCOUNT,
    UPDATE_DISCOUNT,
    DELETE_DISCOUNT,
    GET_DISCOUNT_BY_ID,
    GET_DISCOUNTS,

    // INVENTORY
    CREATE_INVENTORY,
    UPDATE_INVENTORY,
    DELETE_INVENTORY,
    GET_INVENTORY_BY_ID,
    GET_INVENTORIES,

    // INVOICE
    CREATE_INVOICE,
    UPDATE_INVOICE,
    DELETE_INVOICE,
    GET_INVOICE_BY_ID,
    GET_INVOICES,

    // ORDER
    CREATE_ORDER,
    UPDATE_ORDER,
    DELETE_ORDER,
    GET_ORDER_BY_ID,
    GET_ORDERS,

    // ORDER_ITEM
    CREATE_ORDER_ITEM,
    UPDATE_ORDER_ITEM,
    DELETE_ORDER_ITEM,
    GET_ORDER_ITEM_BY_ID,
    GET_ORDER_ITEMS,

    // PAYMENT
    CREATE_PAYMENT,
    UPDATE_PAYMENT,
    DELETE_PAYMENT,
    GET_PAYMENT_BY_ID,
    GET_PAYMENTS,

    // PERMISSION
    CREATE_PERMISSION,
    UPDATE_PERMISSION,
    DELETE_PERMISSION,
    GET_PERMISSION_BY_ID,
    GET_PERMISSIONS,

    // PRODUCT_ATTRIBUTE
    CREATE_PRODUCT_ATTRIBUTE,
    UPDATE_PRODUCT_ATTRIBUTE,
    DELETE_PRODUCT_ATTRIBUTE,
    GET_PRODUCT_ATTRIBUTE_BY_ID,
    GET_PRODUCT_ATTRIBUTES,

    // PRODUCT_ATTRIBUTE_VALUE
    CREATE_PRODUCT_ATTRIBUTE_VALUE,
    UPDATE_PRODUCT_ATTRIBUTE_VALUE,
    DELETE_PRODUCT_ATTRIBUTE_VALUE,
    GET_PRODUCT_ATTRIBUTE_VALUE_BY_ID,
    GET_PRODUCT_ATTRIBUTE_VALUES,

    // PRODUCT
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    GET_PRODUCT_BY_ID,
    GET_PRODUCTS,

    // PRODUCT_VARIANT
    CREATE_PRODUCT_VARIANT,
    UPDATE_PRODUCT_VARIANT,
    DELETE_PRODUCT_VARIANT,
    GET_PRODUCT_VARIANT_BY_ID,
    GET_PRODUCT_VARIANTS,

    // REVIEW
    CREATE_REVIEW,
    UPDATE_REVIEW,
    DELETE_REVIEW,
    GET_REVIEW_BY_ID,
    GET_REVIEWS,

    // ROLE
    CREATE_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,
    GET_ROLE_BY_ID,
    GET_ROLES,

    // ROLE_PERMISSION
    CREATE_ROLE_PERMISSION,
    UPDATE_ROLE_PERMISSION,
    DELETE_ROLE_PERMISSION,
    GET_ROLE_PERMISSION_BY_ID,
    GET_ROLE_PERMISSIONS,
}
